apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
  namespace: oficina-mecanica
  labels:
    app.kubernetes.io/name: oficina-mecanica
data:
  PORT: "4000"
  CORS_ORIGIN: "http://localhost:3000"
  POSTGRES_DB: "oficina"
  POSTGRES_USER: "postgres"
  NEW_RELIC_APP_NAME: "oficina-mecanica-api"
  LOG_LEVEL: "info"
